#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/config.php';

use App\Core\Application\App;
use App\Core\Console\Console;

App::boot();

$console = new Console();

$console->run($argv);