<?php require_once __DIR__ . '/../components/component.php'; ?>
<section class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <?php render_component('breadcrumb', ['items' => [['label' => 'Home', 'href' => '/'], ['label' => 'Documentation', 'href' => '/docs'], ['label' => $currentDoc['title'] ?? '']]]); ?>
    <div class="mt-5 lg:hidden"><details class="rounded-xl border border-zp-border bg-zp-surface/75 p-1"><summary class="flex cursor-pointer items-center justify-between rounded-lg px-3 py-2 text-sm font-semibold text-zp-ink">Browse documentation <span class="text-zp-link" aria-hidden="true">⌄</span></summary><nav class="max-h-72 overflow-y-auto border-t border-zp-border px-2 py-2" aria-label="Documentation navigation"><ul class="space-y-1"><?php foreach (($documents ?? []) as $doc): ?><li><a href="/docs/<?= htmlspecialchars($doc['slug'], ENT_QUOTES, 'UTF-8') ?>" class="block rounded-lg px-3 py-2 text-sm <?= ($currentDoc['slug'] ?? '') === $doc['slug'] ? 'bg-teal-500/10 font-semibold text-zp-link' : 'text-zp-desc hover:bg-zp-bg hover:text-zp-ink' ?>"><?= htmlspecialchars($doc['title'], ENT_QUOTES, 'UTF-8') ?></a></li><?php endforeach; ?></ul></nav></details></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)_190px]">
        <?php render_component('sidebar', ['documents' => $documents ?? [], 'currentSlug' => $currentDoc['slug'] ?? '']); ?>
        <article class="min-w-0 rounded-2xl border border-zp-border bg-zp-surface/80 p-6 shadow-sm lg:p-10">
            <div class="mb-8 border-b border-zp-border pb-6"><p class="text-xs font-bold uppercase tracking-[.14em] text-zp-link">Documentation</p><h1 class="mt-2 font-display text-3xl font-bold tracking-[-.035em] text-zp-ink"><?= htmlspecialchars($currentDoc['title'] ?? '', ENT_QUOTES, 'UTF-8') ?></h1></div>
            <div class="prose prose-slate dark:prose-invert max-w-none prose-headings:scroll-mt-28 prose-headings:font-semibold prose-headings:text-zp-ink prose-a:text-zp-link prose-a:font-medium prose-strong:text-zp-ink prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:text-sm prose-code:font-normal prose-code:font-[inherit] prose-pre:bg-transparent prose-pre:p-0 prose-blockquote:border-teal-500/40 prose-blockquote:bg-teal-500/5 prose-blockquote:py-1 prose-blockquote:px-4 prose-blockquote:rounded-r-lg prose-li:marker:text-zp-muted"><?= $docHtml ?? '' ?></div>
            <?php render_component('pagination', ['previous' => $previous ?? null, 'next' => $next ?? null]); ?>
        </article>
        <aside class="hidden h-fit rounded-2xl border border-zp-border bg-zp-surface/75 p-4 shadow-sm lg:sticky lg:top-24 lg:block" data-toc><h2 class="text-xs font-semibold uppercase tracking-widest text-zp-muted">On this page</h2><nav class="mt-3" aria-label="Table of contents"><ul class="space-y-1 text-sm"><?php foreach (($toc ?? []) as $item): ?><li style="padding-left: <?= (($item['level'] ?? 2) - 2) * 12 ?>px"><a href="#<?= htmlspecialchars($item['id'], ENT_QUOTES, 'UTF-8') ?>" data-toc-link class="block rounded px-2 py-1 text-zp-muted transition hover:text-zp-link focus-ring border-l-2 border-transparent hover:border-teal-500/50"><?= htmlspecialchars($item['title'], ENT_QUOTES, 'UTF-8') ?></a></li><?php endforeach; ?></ul></nav></aside>
    </div>
</section>
<script>
(function () { var links = document.querySelectorAll('[data-toc-link]'); var headings = []; links.forEach(function (link) { var target = document.getElementById(link.getAttribute('href').slice(1)); if (target) headings.push({ element: target, link: link }); }); if (!headings.length || !('IntersectionObserver' in window)) return; var observer = new IntersectionObserver(function (entries) { entries.forEach(function (entry) { if (!entry.isIntersecting) return; links.forEach(function (link) { link.classList.remove('text-zp-link', 'font-medium', 'border-teal-500/70'); link.classList.add('border-transparent'); }); var current = headings.find(function (heading) { return heading.element === entry.target; }); if (current) { current.link.classList.add('text-zp-link', 'font-medium', 'border-teal-500/70'); current.link.classList.remove('border-transparent'); } }); }, { threshold: 0, rootMargin: '-85px 0px -60% 0px' }); headings.forEach(function (heading) { observer.observe(heading.element); }); })();
</script>
