name: Deploy ZeroPing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script_stop: true

          script: |
            echo "🚀 Starting deployment..."

            ~/scripts/deploy.sh

            echo "📦 Checking containers..."
            docker compose -f ~/ZeroPing/docker-compose.yml ps

            echo "❤️ Checking application..."
            curl --fail --silent --show-error http://localhost/up

            echo "✅ Deployment completed successfully."